DELETE  FROM USERS;
CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
    );


ALTER TABLE users ALTER COLUMN ID RESTART WITH 1;



DELETE  FROM items;
CREATE TABLE IF NOT EXISTS items (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     item_name varchar(255) NOT NULL,
    description varchar(512) NOT NULL,
    available bool NOT NULL,
    owner_id int NOT NULL,
    CONSTRAINT items_pk PRIMARY KEY (id)
    );

ALTER TABLE items ALTER COLUMN ID RESTART WITH 1;



DELETE  FROM bookings;
create table  IF NOT EXISTS bookings
(
    id         bigint generated by default as identity
        constraint pk_booking
            primary key,
    start_date timestamp not null,
    end_date   timestamp not null,
    item_id    bigint    not null
        references items
            on delete cascade,
    booker_id  bigint    not null
        references users
            on delete cascade,
    status     varchar(10)
);

ALTER TABLE bookings ALTER COLUMN ID RESTART WITH 1;





DELETE  FROM comments;
create table   IF NOT EXISTS comments
(
    id        bigint generated by default as identity
        constraint pk_comments
            primary key,
    text      varchar(1000) not null,
    item_id   bigint        not null
        references items
            on delete cascade,
    author_id bigint        not null
        references users
            on delete cascade,
    created   timestamp
);

ALTER TABLE comments ALTER COLUMN ID RESTART WITH 1;




DELETE  FROM REQUESTS;
create table IF NOT EXISTS REQUESTS
(
    ID           BIGINT auto_increment,
    DESCRIPTION  CHARACTER VARYING(1000) not null,
    REQUESTOR_ID BIGINT
        references USERS
            on delete cascade,
    CREATED      TIMESTAMP,
    constraint PK_REQUEST
        primary key (ID)
);

ALTER TABLE REQUESTS ALTER COLUMN ID RESTART WITH 1;